name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  build_and_push:
    name: Build and push Docker image to Docker Hub
    
    runs-on: ubuntu-latest
    
    env:
      LOGIN: ${{ secrets.DOCKER_USERNAME }}
      NAME: ${{ github.event.repository.name }}
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: docker build -t $LOGIN/$NAME:latest -f Dockerfile .
        
      - name: Run Docker Image
        run: docker run -p 8080:80 -d $LOGIN/$NAME:latest 
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Test with pytest
        run: |
          pytest
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Push Docker Image
        run: docker push $LOGIN/$NAME:latest
      
